'use client';

import React, { createContext, useContext, useEffect, useState } from "react";

type Lang = "th" | "en";

type LanguageContextValue = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
};

const translations: Record<string, { th: string; en: string }> = {
  "hello": { th: "สวัสดี", en: "Hello" },

  // Sidebar — group headers
  "sidebar.group.main": { th: "หลัก", en: "Main" },
  "sidebar.group.docs": { th: "เอกสาร", en: "Documents" },
  "sidebar.group.master": { th: "ข้อมูลหลัก", en: "Master Data" },
  "sidebar.group.org": { th: "องค์กร", en: "Organization" },
  "sidebar.group.system": { th: "ระบบ", en: "System" },
  "sidebar.group.pending": { th: "รออนุมัติ", en: "Pending" },
  "sidebar.group.create": { th: "สร้างเอกสาร", en: "Create" },
  "sidebar.group.team": { th: "ทีม", en: "Team" },
  "sidebar.group.all_data": { th: "ข้อมูลทั้งหมด", en: "All Data" },

  // Sidebar — nav items
  "sidebar.dashboard": { th: "แดชบอร์ด", en: "Dashboard" },
  "sidebar.reports": { th: "รายงาน", en: "Reports" },
  "sidebar.reports_team": { th: "รายงานทีม", en: "Team Reports" },
  "sidebar.customer_requests": { th: "คำขอเพิ่มลูกค้า", en: "Customer Requests" },
  "sidebar.orders": { th: "คำสั่งซื้อ", en: "Orders" },
  "sidebar.orders_pending": { th: "คำสั่งซื้อรอตรวจสอบ", en: "Orders Pending Review" },
  "sidebar.quotations_pending": { th: "ใบเสนอราคารออนุมัติ", en: "Quotations Pending" },
  "sidebar.manage_customers": { th: "จัดการลูกค้า", en: "Manage Customers" },
  "sidebar.manage_products": { th: "จัดการสินค้า", en: "Manage Products" },
  "sidebar.manage_users": { th: "จัดการผู้ใช้", en: "Manage Users" },
  "sidebar.manage_teams": { th: "จัดการทีม", en: "Manage Teams" },
  "sidebar.zones": { th: "เขตการขาย", en: "Sales Zones" },
  "sidebar.activity_logs": { th: "บันทึกการใช้งาน", en: "Activity Logs" },
  "sidebar.create_quotation": { th: "สร้างใบเสนอราคา", en: "Create Quotation" },
  "sidebar.create_order": { th: "สร้างคำสั่งซื้อ", en: "Create Order" },
  "sidebar.request_customer": { th: "ขอเพิ่มลูกค้า", en: "Request New Customer" },
  "sidebar.my_documents": { th: "เอกสารของฉัน", en: "My Documents" },
  "sidebar.team_documents": { th: "เอกสารทีม", en: "Team Documents" },
  "sidebar.info_customers": { th: "ข้อมูลลูกค้า", en: "Customers" },
  "sidebar.info_products": { th: "ข้อมูลสินค้า", en: "Products" },
  "sidebar.team_members": { th: "สมาชิกทีม", en: "Team Members" },
  "sidebar.all_customers": { th: "ลูกค้าทั้งหมด", en: "All Customers" },
  "sidebar.all_products": { th: "สินค้าทั้งหมด", en: "All Products" },
  "sidebar.all_users": { th: "ผู้ใช้ทั้งหมด", en: "All Users" },
  "sidebar.all_teams": { th: "ทีมทั้งหมด", en: "All Teams" },

  // Roles
  "role.admin": { th: "ผู้ดูแลระบบ", en: "Administrator" },
  "role.manager": { th: "ผู้จัดการทีม", en: "Team Manager" },
  "role.sales": { th: "พนักงานขาย", en: "Sales" },
  "role.cfo": { th: "ผู้บริหาร", en: "Executive" },

  // Sidebar — misc
  "sidebar.close_menu": { th: "ปิดเมนู", en: "Close menu" },
  "sidebar.new_count": { th: "ใหม่", en: "new" },

  // TopBar
  "topbar.notifications":        { th: "การแจ้งเตือน",          en: "Notifications" },
  "topbar.mark_all_read":        { th: "อ่านทั้งหมด",           en: "Mark all read" },
  "topbar.no_notifications":     { th: "ไม่มีการแจ้งเตือน",     en: "No notifications" },
  "topbar.click_to_view":        { th: "กดเพื่อดู →",           en: "Click to view →" },
  "topbar.change_language":      { th: "เปลี่ยนภาษา",           en: "Change language" },
  "topbar.user_menu":            { th: "เมนูผู้ใช้",            en: "User menu" },
  "topbar.team":                 { th: "ทีม",                   en: "Team" },
  "topbar.logout":               { th: "ออกจากระบบ",            en: "Log out" },
  "topbar.expand_menu":          { th: "ขยายเมนู",              en: "Expand menu" },
  "topbar.collapse_menu":        { th: "ย่อเมนู",               en: "Collapse menu" },
  "topbar.open_menu":            { th: "เปิดเมนู",              en: "Open menu" },

  // Common table / list controls
  "common.search":               { th: "ค้นหา...",              en: "Search..." },
  "common.search_customers":     { th: "ค้นหาลูกค้า...",        en: "Search customers..." },
  "common.search_products":      { th: "ค้นหาสินค้า...",        en: "Search products..." },
  "common.records":              { th: "รายการ",                en: "records" },
  "common.actions":              { th: "จัดการ",                en: "Actions" },
  "common.view_details":         { th: "ดูรายละเอียด",          en: "View" },
  "common.no_data":              { th: "ไม่พบข้อมูล",           en: "No data" },
  "common.close":                { th: "ปิด",                   en: "Close" },
  "common.cancel":               { th: "ยกเลิก",                en: "Cancel" },
  "common.save":                 { th: "บันทึก",                en: "Save" },
  "common.saving":               { th: "บันทึก...",             en: "Saving..." },
  "common.saving_dots":          { th: "กำลังบันทึก…",           en: "Saving…" },
  "common.edit":                 { th: "แก้ไข",                 en: "Edit" },
  "common.delete":               { th: "ลบ",                    en: "Delete" },
  "common.add":                  { th: "เพิ่ม",                 en: "Add" },
  "common.confirm":              { th: "ยืนยัน",                en: "Confirm" },
  "common.optional":             { th: "-- ไม่ระบุ --",         en: "-- Optional --" },
  "common.required_mark":        { th: "*",                     en: "*" },
  "common.showing":              { th: "แสดง",                  en: "Showing" },
  "common.of":                   { th: "จาก",                   en: "of" },
  "common.all_categories":       { th: "หมวดหมู่ทั้งหมด",       en: "All categories" },

  // Customers table
  "customers.col.company":       { th: "ชื่อบริษัท",            en: "Company" },
  "customers.col.contact":       { th: "ผู้ติดต่อ",             en: "Contact" },
  "customers.col.phone":         { th: "เบอร์",                 en: "Phone" },
  "customers.col.address":       { th: "ที่อยู่",               en: "Address" },
  "customers.detail.added_at":   { th: "เพิ่มเมื่อ",            en: "Added on" },
  "customers.detail.address":    { th: "ที่อยู่",               en: "Address" },
  "customers.detail.contact":    { th: "ผู้ติดต่อ",             en: "Contact" },
  "customers.detail.phone":      { th: "เบอร์โทร",              en: "Phone" },
  "customers.detail.email":      { th: "อีเมล",                 en: "Email" },
  "customers.detail.drug_lic":   { th: "เลขอนุญาตขายยา",        en: "Drug License No." },
  "customers.detail.docs":       { th: "เอกสารและรูปภาพ",       en: "Documents & Images" },
  "customers.detail.img_location":  { th: "รูปสถานที่",         en: "Location Photo" },
  "customers.detail.img_drug":      { th: "ใบอนุญาตขายยา",      en: "Drug License" },
  "customers.detail.img_hospital":  { th: "ใบอนุญาตสถานพยาบาล", en: "Hospital License" },

  // Customer form
  "cf.company_info":             { th: "ข้อมูลบริษัท",          en: "Company Info" },
  "cf.tax_license_info":         { th: "ข้อมูลภาษีและใบอนุญาต",  en: "Tax & License Info" },
  "cf.images_docs":              { th: "รูปภาพและเอกสาร",       en: "Images & Documents" },
  "cf.upload_hint":              { th: "อัพโหลดรูปจากเครื่อง (ไม่เกิน 2MB ต่อรูป)", en: "Upload from device (max 2MB each)" },
  "cf.customer_code":            { th: "รหัสลูกค้า",            en: "Customer Code" },
  "cf.auto_gen_hint":            { th: "ปล่อยว่างเพื่อ auto-gen", en: "Leave empty to auto-generate" },
  "cf.zone":                     { th: "เขตการขาย",             en: "Sales Zone" },
  "cf.company_name":             { th: "ชื่อบริษัท",            en: "Company Name" },
  "cf.address":                  { th: "ที่อยู่",               en: "Address" },
  "cf.contact_name":             { th: "ชื่อผู้ติดต่อ",         en: "Contact Name" },
  "cf.phone":                    { th: "เบอร์โทรศัพท์",         en: "Phone" },
  "cf.email":                    { th: "อีเมล",                 en: "Email" },
  "cf.has_tax_id":               { th: "มีเลขผู้เสียภาษีหรือไม่?", en: "Has Tax ID?" },
  "cf.has":                      { th: "มี",                    en: "Yes" },
  "cf.no":                       { th: "ไม่มี",                 en: "No" },
  "cf.tax_id":                   { th: "เลขประจำตัวผู้เสียภาษี", en: "Tax ID Number" },
  "cf.drug_license_no":          { th: "เลขที่อนุญาตขายยา",      en: "Drug License No." },
  "cf.upload":                   { th: "อัพโหลดรูป",             en: "Upload image" },
  "cf.file_too_big":             { th: "ไฟล์ใหญ่เกิน 2MB",       en: "File exceeds 2MB" },
  "cf.save_failed":              { th: "บันทึกไม่สำเร็จ",        en: "Save failed" },
  "cf.request_failed":           { th: "ส่งคำขอไม่สำเร็จ",      en: "Request failed" },
  "cf.send_request":             { th: "ส่งคำขอ",               en: "Send request" },
  "cf.created_ok":               { th: "เพิ่มลูกค้าเรียบร้อย",   en: "Customer added" },
  "cf.updated_ok":                { th: "แก้ไขเรียบร้อย",       en: "Updated" },
  "cf.requested_ok":             { th: "ส่งคำขอเรียบร้อย รอผู้ดูแลตรวจสอบ", en: "Request sent, awaiting admin review" },
  "cf.img_location":             { th: "รูปสถานที่",            en: "Location Photo" },
  "cf.img_drug":                 { th: "ใบอนุญาตขายยา",         en: "Drug License" },
  "cf.img_hospital":             { th: "ใบอนุญาตสถานพยาบาล",    en: "Hospital License" },
  "cf.placeholder_tax":          { th: "เช่น 0105560001234",     en: "e.g. 0105560001234" },

  // Products table
  "products.col.code":           { th: "รหัส",                  en: "Code" },
  "products.col.name":           { th: "ชื่อสินค้า",            en: "Product Name" },
  "products.col.category":       { th: "หมวดหมู่",              en: "Category" },
  "products.col.stock":          { th: "คงเหลือ",               en: "Stock" },
  "products.col.price":          { th: "ราคา/หน่วย",            en: "Unit Price" },
  "products.col.unit":           { th: "หน่วย",                 en: "Unit" },
  "products.col.status":         { th: "สถานะ",                 en: "Status" },
  "products.status.available":   { th: "พร้อมขาย",              en: "Available" },
  "products.status.unavailable": { th: "ไม่พร้อมขาย",           en: "Unavailable" },
  "products.no_image":           { th: "ไม่มีรูปสินค้า",        en: "No product image" },
  "products.no_category":        { th: "ไม่ระบุหมวด",           en: "Uncategorized" },
  "products.stock_left":         { th: "คงเหลือในสต๊อก",        en: "Stock Remaining" },
  "products.sale_price_per":     { th: "ราคาขายต่อหน่วย",       en: "Sale Price / Unit" },
  "products.unit_label":         { th: "หน่วย",                 en: "unit" },
  "products.low_stock":          { th: "⚠ ใกล้หมด",             en: "⚠ Low stock" },
  "products.out_of_stock":       { th: "หมดสต๊อก",              en: "Out of stock" },
  "products.lot_dates":          { th: "ข้อมูลล็อต / วันที่",   en: "Lot / Dates" },
  "products.lot_no":             { th: "เลขล็อต",               en: "Lot No." },
  "products.mfg_date":           { th: "วันผลิต",               en: "Mfg. Date" },
  "products.exp_date":           { th: "วันหมดอายุ",            en: "Exp. Date" },
  "products.updated_at":         { th: "อัปเดตล่าสุด",          en: "Last updated" },

  // Zones
  "zones.title":                 { th: "เขตการขาย",             en: "Sales Zones" },
  "zones.add":                   { th: "เพิ่มเขต",              en: "Add Zone" },
  "zones.add_new":               { th: "เพิ่มเขตการขายใหม่",    en: "Add New Zone" },
  "zones.edit":                  { th: "แก้ไขเขตการขาย",        en: "Edit Sales Zone" },
  "zones.col.code":              { th: "รหัส",                  en: "Code" },
  "zones.col.name":              { th: "ชื่อเขต",               en: "Zone Name" },
  "zones.col.province":          { th: "จังหวัด",               en: "Province" },
  "zones.col.region":            { th: "ภาค",                   en: "Region" },
  "zones.empty":                 { th: "ยังไม่มีเขตการขาย — กด \"เพิ่มเขต\" เพื่อสร้าง", en: "No sales zones — click \"Add Zone\" to create" },
  "zones.field.code":            { th: "รหัสเขต",               en: "Zone Code" },
  "zones.field.name":            { th: "ชื่อเขต",               en: "Zone Name" },
  "zones.field.province":        { th: "จังหวัด",               en: "Province" },
  "zones.field.region":          { th: "ภาค",                   en: "Region" },
  "zones.field.description":     { th: "คำอธิบาย",              en: "Description" },
  "zones.placeholder.code":      { th: "เช่น BKK, CNX, S-01",   en: "e.g. BKK, CNX, S-01" },
  "zones.placeholder.name":      { th: "เช่น กรุงเทพและปริมณฑล", en: "e.g. Bangkok & Perimeter" },
  "zones.placeholder.province":  { th: "เช่น กรุงเทพมหานคร",    en: "e.g. Bangkok" },
  "zones.confirm_delete":        { th: "ลบเขตการขาย \"{code} - {name}\"?", en: "Delete sales zone \"{code} - {name}\"?" },
  "zones.region.central":        { th: "ภาคกลาง",               en: "Central" },
  "zones.region.north":          { th: "ภาคเหนือ",              en: "Northern" },
  "zones.region.south":          { th: "ภาคใต้",                en: "Southern" },
  "zones.region.east":           { th: "ภาคตะวันออก",           en: "Eastern" },
  "zones.region.northeast":      { th: "ภาคตะวันออกเฉียงเหนือ", en: "Northeastern" },
  "zones.region.west":           { th: "ภาคตะวันตก",            en: "Western" },

  // Common
  "common.loading":              { th: "กำลังโหลด...",          en: "Loading..." },
  "common.view_all":             { th: "ดูทั้งหมด",             en: "View all" },
  "common.no_data_generic":      { th: "ยังไม่มีข้อมูล",         en: "No data" },

  // Dashboard — titles
  "dashboard.title":             { th: "แดชบอร์ด",              en: "Dashboard" },
  "dashboard.title_admin":       { th: "แดชบอร์ด - ผู้ดูแลระบบ", en: "Dashboard - Administrator" },
  "dashboard.title_manager":     { th: "แดชบอร์ด - ผู้จัดการทีม", en: "Dashboard - Team Manager" },
  "dashboard.title_cfo":         { th: "แดชบอร์ด - ผู้บริหาร",    en: "Dashboard - Executive" },
  "dashboard.no_team":           { th: "คุณยังไม่ได้ถูกมอบหมายให้อยู่ในทีมใด กรุณาติดต่อผู้ดูแลระบบ", en: "You haven't been assigned to a team. Please contact your administrator." },

  // Dashboard — stat cards
  "dashboard.stat.total_users":     { th: "ผู้ใช้ทั้งหมด",      en: "Total Users" },
  "dashboard.stat.customers":       { th: "ลูกค้า",             en: "Customers" },
  "dashboard.stat.products":        { th: "สินค้า",             en: "Products" },
  "dashboard.stat.total_teams":     { th: "ทีมทั้งหมด",         en: "Total Teams" },
  "dashboard.stat.total_orders":    { th: "คำสั่งซื้อทั้งหมด",   en: "Total Orders" },
  "dashboard.stat.pending":         { th: "รอดำเนินการ",         en: "Pending" },
  "dashboard.stat.customer_reqs":   { th: "คำขอเพิ่มลูกค้า",     en: "Customer Requests" },
  "dashboard.stat.low_stock":       { th: "สินค้าใกล้หมด",       en: "Low Stock" },
  "dashboard.stat.total_quotations":{ th: "ใบเสนอราคาทั้งหมด",   en: "Total Quotations" },
  "dashboard.stat.pending_approval":{ th: "รออนุมัติ",           en: "Pending Approval" },
  "dashboard.stat.pending_review":  { th: "รอตรวจสอบ",           en: "Pending Review" },
  "dashboard.stat.rejected":        { th: "ถูกปฏิเสธ",           en: "Rejected" },
  "dashboard.stat.team_sales":      { th: "ยอดขายทีม",           en: "Team Sales" },
  "dashboard.stat.total_sales":     { th: "ยอดขายรวม",           en: "Total Sales" },
  "dashboard.stat.orders":          { th: "คำสั่งซื้อ",         en: "Orders" },
  "dashboard.stat.quotations":      { th: "ใบเสนอราคา",         en: "Quotations" },
  "dashboard.stat.customer_count":  { th: "จำนวนลูกค้า",         en: "Customer Count" },

  // Dashboard — chart titles + tooltips
  "dashboard.chart.monthly_revenue":  { th: "ยอดขายรายเดือน (6 เดือนล่าสุด)",   en: "Monthly Revenue (Last 6 Months)" },
  "dashboard.chart.monthly_orders":   { th: "จำนวนคำสั่งซื้อรายเดือน",          en: "Monthly Order Count" },
  "dashboard.chart.order_status":     { th: "สถานะคำสั่งซื้อ",                 en: "Order Status" },
  "dashboard.chart.team_sales":       { th: "ยอดขายของทีม (6 เดือนล่าสุด)",     en: "Team Sales (Last 6 Months)" },
  "dashboard.chart.quotation_status": { th: "สถานะใบเสนอราคา",                 en: "Quotation Status" },
  "dashboard.chart.tooltip_sales":    { th: "ยอดขาย",                         en: "Sales" },
  "dashboard.chart.tooltip_orders":   { th: "คำสั่งซื้อ",                     en: "Orders" },

  // Dashboard — sections
  "dashboard.section.recent_orders":     { th: "คำสั่งซื้อล่าสุด",       en: "Recent Orders" },
  "dashboard.section.low_stock":         { th: "สินค้าใกล้หมด",          en: "Low Stock Products" },
  "dashboard.section.top_products":      { th: "สินค้าขายดี Top 5",      en: "Top 5 Products" },
  "dashboard.section.top_customers":     { th: "ลูกค้าที่ซื้อสูงสุด Top 5", en: "Top 5 Customers" },
  "dashboard.section.team_performance":  { th: "ผลงานแต่ละทีม",          en: "Team Performance" },
  "dashboard.team_hint":                 { th: "ดูรายงานละเอียดในหน้ารายงาน", en: "See details in Reports" },

  // Dashboard — empty states
  "dashboard.empty.no_orders":      { th: "ยังไม่มีคำสั่งซื้อ",   en: "No orders yet" },
  "dashboard.empty.all_in_stock":   { th: "สินค้าทุกชิ้นมีพอ",    en: "All products in stock" },
  "dashboard.empty.no_sales":       { th: "ยังไม่มียอดขาย",       en: "No sales yet" },
  "dashboard.empty.no_quotations":  { th: "ยังไม่มีใบเสนอราคา",   en: "No quotations yet" },

  // Dashboard — stock indicators
  "dashboard.stock.out":            { th: "หมด",                 en: "Out" },
  "dashboard.stock.left":           { th: "เหลือ",               en: "Left" },

  // Order/Quotation statuses
  "status.draft":            { th: "ร่าง",         en: "Draft" },
  "status.pending_review":   { th: "รอตรวจสอบ",   en: "Pending Review" },
  "status.processing":       { th: "ดำเนินการ",   en: "Processing" },
  "status.completed":        { th: "เสร็จสิ้น",   en: "Completed" },
  "status.rejected":         { th: "ไม่ผ่าน",     en: "Rejected" },
  "status.pending":          { th: "รออนุมัติ",   en: "Pending" },
  "status.approved":         { th: "อนุมัติ",     en: "Approved" },
  "status.cancelled":        { th: "ยกเลิก",      en: "Cancelled" },

  // Months (short)
  "month.jan": { th: "ม.ค.", en: "Jan" },
  "month.feb": { th: "ก.พ.", en: "Feb" },
  "month.mar": { th: "มี.ค.", en: "Mar" },
  "month.apr": { th: "เม.ย.", en: "Apr" },
  "month.may": { th: "พ.ค.", en: "May" },
  "month.jun": { th: "มิ.ย.", en: "Jun" },
  "month.jul": { th: "ก.ค.", en: "Jul" },
  "month.aug": { th: "ส.ค.", en: "Aug" },
  "month.sep": { th: "ก.ย.", en: "Sep" },
  "month.oct": { th: "ต.ค.", en: "Oct" },
  "month.nov": { th: "พ.ย.", en: "Nov" },
  "month.dec": { th: "ธ.ค.", en: "Dec" },

  // Users page
  "users.title":              { th: "จัดการผู้ใช้",          en: "Manage Users" },
  "users.title_all":          { th: "ผู้ใช้ทั้งหมด",         en: "All Users" },
  "users.title_detail":       { th: "ข้อมูลผู้ใช้",          en: "User Details" },
  "users.add":                { th: "เพิ่มผู้ใช้",           en: "Add User" },
  "users.add_new":            { th: "เพิ่มผู้ใช้ใหม่",       en: "Add New User" },
  "users.edit":               { th: "แก้ไขผู้ใช้",           en: "Edit User" },
  "users.detail":             { th: "รายละเอียดผู้ใช้",       en: "User Details" },
  "users.col.name":           { th: "ชื่อ-นามสกุล",          en: "Full Name" },
  "users.col.email":          { th: "อีเมล",                 en: "Email" },
  "users.col.role":           { th: "บทบาท",                 en: "Role" },
  "users.col.team":           { th: "ทีม",                   en: "Team" },
  "users.col.status":         { th: "สถานะ",                 en: "Status" },
  "users.status.active":      { th: "ใช้งาน",                en: "Active" },
  "users.status.inactive":    { th: "ปิด",                   en: "Inactive" },
  "users.no_users":           { th: "ไม่พบผู้ใช้",           en: "No users found" },
  "users.field.role":         { th: "บทบาท:",                en: "Role:" },
  "users.field.team":         { th: "ทีม:",                  en: "Team:" },
  "users.field.phone":        { th: "เบอร์โทร:",             en: "Phone:" },
  "users.field.status":       { th: "สถานะ:",                en: "Status:" },
  "users.field.created_at":   { th: "วันที่สร้าง:",           en: "Created:" },
  "users.detail.phone":       { th: "เบอร์โทรศัพท์",         en: "Phone" },
  "users.detail.team":        { th: "ทีม",                   en: "Team" },
  "users.detail.status":      { th: "สถานะ",                 en: "Status" },
  "users.detail.created_at":  { th: "วันที่สร้างบัญชี",       en: "Account Created" },
  "users.form.first_name":    { th: "ชื่อ *",                en: "First Name *" },
  "users.form.last_name":     { th: "นามสกุล *",             en: "Last Name *" },
  "users.form.email":         { th: "อีเมล *",               en: "Email *" },
  "users.form.password":      { th: "รหัสผ่าน",              en: "Password" },
  "users.form.password_edit_hint": { th: "(เว้นว่างไว้หากไม่เปลี่ยน)", en: "(leave blank to keep current)" },
  "users.form.password_new_hint":  { th: "* (อย่างน้อย 6 ตัว)", en: "* (min 6 characters)" },
  "users.form.phone":         { th: "เบอร์โทร",              en: "Phone" },
  "users.form.role":          { th: "บทบาท",                 en: "Role" },
  "users.form.team":          { th: "ทีม",                   en: "Team" },
  "users.form.zone":          { th: "เขตการขาย",             en: "Sales Zone" },
  "users.form.no_team":       { th: "-- ไม่มีทีม --",        en: "-- No Team --" },
  "users.form.no_zone":       { th: "-- ไม่ระบุเขต --",      en: "-- No Zone --" },
  "users.confirm_delete":     { th: "ลบผู้ใช้ {name}?",       en: "Delete user {name}?" },

  // Roles (short form for tables)
  "role.short.admin":   { th: "ผู้ดูแล",     en: "Admin" },
  "role.short.manager": { th: "ผู้จัดการ",   en: "Manager" },
  "role.short.sales":   { th: "พนักงานขาย", en: "Sales" },
  "role.short.cfo":     { th: "ผู้บริหาร",   en: "CFO" },

  // Order statuses (distinct wording from dashboard aggregate labels)
  "doc.status.pending_review": { th: "รอตรวจสอบ",        en: "Pending Review" },
  "doc.status.processing":     { th: "รอยืนยันการขาย",    en: "Awaiting Sale Confirmation" },
  "doc.status.completed":      { th: "สำเร็จ",            en: "Completed" },
  "doc.status.cancelled":      { th: "ยกเลิก",            en: "Cancelled" },
  "doc.status.rejected":       { th: "ไม่ผ่าน",           en: "Rejected" },
  // Quotation statuses
  "doc.status.draft":          { th: "ฉบับร่าง",          en: "Draft" },
  "doc.status.pending":        { th: "รออนุมัติ",         en: "Pending" },
  "doc.status.approved":       { th: "อนุมัติ",           en: "Approved" },
  "doc.status.ordered":        { th: "ออกคำสั่งซื้อแล้ว", en: "Order Placed" },
  "doc.status.rejected_q":     { th: "ไม่อนุมัติ",        en: "Not Approved" },

  // Common document fields / actions
  "doc.order":              { th: "คำสั่งซื้อ",          en: "Order" },
  "doc.quotation":           { th: "ใบเสนอราคา",         en: "Quotation" },
  "doc.number":              { th: "เลขที่",              en: "No." },
  "doc.customer":            { th: "ลูกค้า",              en: "Customer" },
  "doc.creator":             { th: "ผู้สร้าง",            en: "Created By" },
  "doc.creator_full":        { th: "ผู้สร้างเอกสาร",       en: "Document Creator" },
  "doc.value":               { th: "มูลค่า",              en: "Value" },
  "doc.status_col":          { th: "สถานะ",               en: "Status" },
  "doc.date":                { th: "วันที่",              en: "Date" },
  "doc.type":                { th: "ประเภท",              en: "Type" },
  "doc.actions":             { th: "จัดการ",              en: "Actions" },
  "doc.view_download_pdf":   { th: "ดู / โหลด PDF",       en: "View / Download PDF" },
  "doc.download_pdf":        { th: "ดาวน์โหลด PDF",       en: "Download PDF" },
  "doc.view_pdf_preview":    { th: "ดูตัวอย่าง PDF",       en: "Preview PDF" },
  "doc.view_details":        { th: "ดูข้อมูล",            en: "View Details" },
  "doc.no_documents":        { th: "ไม่มีเอกสาร",         en: "No documents" },
  "doc.no_orders_pending":   { th: "ไม่มีคำสั่งซื้อที่รอตรวจสอบ", en: "No orders pending review" },
  "doc.no_quotations_pending": { th: "ไม่มีใบเสนอราคาที่รออนุมัติ", en: "No quotations pending approval" },
  "doc.no_orders_found":     { th: "ไม่พบคำสั่งซื้อ",     en: "No orders found" },
  "doc.back":                { th: "ย้อนกลับ",            en: "Back" },
  "doc.cancel":              { th: "ยกเลิก",              en: "Cancel" },
  "doc.confirm_sale":        { th: "ยืนยันการขาย",        en: "Confirm Sale" },
  "doc.confirm_cancel":      { th: "ยืนยันยกเลิก",        en: "Confirm Cancellation" },
  "doc.pass_review":         { th: "ผ่านการตรวจสอบ",      en: "Pass Review" },
  "doc.not_pass":            { th: "ไม่ผ่าน",             en: "Fail" },
  "doc.approve":             { th: "อนุมัติ",             en: "Approve" },
  "doc.not_approve":         { th: "ไม่อนุมัติ",          en: "Reject" },
  "doc.confirm_reject":      { th: "ยืนยัน",              en: "Confirm" },
  "doc.confirm_not_approve": { th: "ยืนยันไม่อนุมัติ",     en: "Confirm Rejection" },
  "doc.reject_reason_cancel":{ th: "เหตุผลที่ยกเลิก *",   en: "Cancellation Reason *" },
  "doc.reject_reason_fail":  { th: "เหตุผลที่ไม่ผ่าน *",  en: "Rejection Reason *" },
  "doc.reject_reason_deny":  { th: "เหตุผลที่ไม่อนุมัติ *", en: "Rejection Reason *" },
  "doc.reason_placeholder":  { th: "ระบุเหตุผล...",       en: "Enter reason..." },
  "doc.reject_reason_label": { th: "เหตุผล",              en: "Reason" },
  "doc.reject_reason_label_deny": { th: "เหตุผลที่ไม่อนุมัติ", en: "Rejection Reason" },
  "doc.status_cannot_change":{ th: "ไม่สามารถเปลี่ยนแปลงได้แล้ว", en: "can no longer be changed" },
  "doc.status_prefix":       { th: "สถานะ",               en: "Status" },
  "doc.edit_number":         { th: "แก้ไขเลขบิล",         en: "Edit Number" },
  "doc.edit_number_full":    { th: "แก้ไขเลขบิลไม่สำเร็จ", en: "Failed to edit number" },
  "doc.edit_draft":          { th: "แก้ไขฉบับร่าง",       en: "Edit Draft" },
  "doc.edit":                { th: "แก้ไข",               en: "Edit" },
  "doc.convert_to_order":    { th: "แปลงเป็นคำสั่งซื้อ",  en: "Convert to Order" },
  "doc.back_to_list":        { th: "กลับไปหน้ารายการ",    en: "Back to List" },
  "doc.current_status":      { th: "สถานะปัจจุบัน:",       en: "Current status:" },
  "doc.by":                  { th: "โดย",                 en: "By" },
  "doc.related_open":        { th: "เปิดเอกสารที่เกี่ยวข้อง", en: "Open related document" },
  "doc.related_from":        { th: "จาก",                 en: "from" },

  // Customer info block
  "doc.customer_info":       { th: "ข้อมูลลูกค้า",        en: "Customer Info" },
  "doc.company_name":        { th: "ชื่อบริษัท:",         en: "Company:" },
  "doc.contact_name":        { th: "ผู้ติดต่อ:",          en: "Contact:" },
  "doc.phone_label":         { th: "เบอร์:",              en: "Phone:" },
  "doc.email_label":         { th: "อีเมล:",              en: "Email:" },
  "doc.address_label":       { th: "ที่อยู่:",            en: "Address:" },
  "doc.field.company":       { th: "บริษัท",              en: "Company" },
  "doc.field.contact":       { th: "ผู้ติดต่อ",           en: "Contact" },
  "doc.field.phone":         { th: "เบอร์โทรศัพท์",       en: "Phone" },
  "doc.field.email":         { th: "อีเมล",               en: "Email" },
  "doc.field.address":       { th: "ที่อยู่",             en: "Address" },
  "doc.phone_short":         { th: "โทร:",                en: "Tel:" },

  // Items table
  "doc.items_title":         { th: "รายการสินค้า",        en: "Items" },
  "doc.items_count":         { th: "รายการสินค้า ({count} รายการ)", en: "Items ({count})" },
  "doc.merged_note":         { th: "รวมรายการซ้ำแล้ว (จริง {count} แถว)", en: "Duplicates merged ({count} rows total)" },
  "doc.rows_count":          { th: "({count} แถว)",       en: "({count} rows)" },
  "doc.col.product":         { th: "สินค้า",              en: "Product" },
  "doc.col.qty":             { th: "จำนวน",               en: "Qty" },
  "doc.col.unit_price":      { th: "ราคา/หน่วย",          en: "Unit Price" },
  "doc.col.unit_price_short":{ th: "ราคา",                en: "Price" },
  "doc.col.negotiated_price":{ th: "ราคาตกลง",            en: "Negotiated Price" },
  "doc.col.total":           { th: "รวม",                 en: "Total" },
  "doc.no_quotations_yet":   { th: "ยังไม่มีรายการสินค้า", en: "No items yet" },

  // Totals
  "doc.subtotal_before_vat": { th: "ยอดก่อน VAT:",        en: "Subtotal (before VAT):" },
  "doc.subtotal_before_adj": { th: "ยอดรวมก่อนปรับ",      en: "Subtotal (before adjustments)" },
  "doc.subtotal_total":      { th: "ยอดรวม:",             en: "Subtotal:" },
  "doc.subtotal_total_noc":  { th: "ยอดรวม",              en: "Subtotal" },
  "doc.vat_line":            { th: "VAT ({pct}%):",       en: "VAT ({pct}%):" },
  "doc.vat_line_noc":        { th: "VAT ({pct}%)",        en: "VAT ({pct}%)" },
  "doc.discount":            { th: "ส่วนลด",              en: "Discount" },
  "doc.other_misc":          { th: "อื่นๆ",               en: "Other" },
  "doc.grand_total":         { th: "ยอดสุทธิ:",           en: "Grand Total:" },
  "doc.grand_total_noc":     { th: "ยอดสุทธิ",            en: "Grand Total" },

  // Notes / contract / reject
  "doc.contract_period":     { th: "ระยะเวลาสัญญา:",       en: "Contract Period:" },
  "doc.contract_period_days":{ th: "วัน",                 en: "days" },
  "doc.notes_label":         { th: "หมายเหตุ:",           en: "Notes:" },
  "doc.notes_title":         { th: "หมายเหตุ",            en: "Notes" },
  "doc.reject_reason_title": { th: "เหตุผลที่ปฏิเสธ:",     en: "Rejection Reason:" },
  "doc.reject_reason_order": { th: "เหตุผล",              en: "Reason" },

  // Search / filters
  "doc.status_all":          { th: "สถานะทั้งหมด",        en: "All Statuses" },
  "doc.tab_all":             { th: "ทั้งหมด",             en: "All" },
  "doc.tab_quotation":       { th: "ใบเสนอราคา",         en: "Quotations" },
  "doc.tab_order":           { th: "คำสั่งซื้อ",          en: "Orders" },
  "doc.phase_active":        { th: "กำลังดำเนินการ",      en: "Active" },
  "doc.phase_finished":      { th: "เสร็จสิ้น",           en: "Finished" },
  "doc.prefix_quotation":    { th: "[ใบเสนอ]",           en: "[Quote]" },
  "doc.prefix_order":        { th: "[คำสั่ง]",           en: "[Order]" },

  // Create order/quotation forms
  "doc.order_info":          { th: "ข้อมูลคำสั่งซื้อ",     en: "Order Info" },
  "doc.general_info":        { th: "ข้อมูลทั่วไป",        en: "General Info" },
  "doc.editing_draft":       { th: "(แก้ไขฉบับร่าง)",     en: "(editing draft)" },
  "doc.select_customer":     { th: "-- เลือกลูกค้า --",   en: "-- Select Customer --" },
  "doc.customer_required":   { th: "ลูกค้า *",            en: "Customer *" },
  "doc.date_label":          { th: "วันที่",              en: "Date" },
  "doc.custom_price_note":   { th: "✓ ลูกค้ารายนี้มีราคาตกลงพิเศษ {count} รายการ", en: "✓ This customer has {count} special negotiated prices" },
  "doc.select_product":      { th: "-- เลือกสินค้า --",   en: "-- Select Product --" },
  "doc.products_from_quote":     { th: "สินค้าจากใบเสนอราคา", en: "Items from Quotation" },
  "doc.products_others":     { th: "สินค้าอื่น ๆ",        en: "Other Products" },
  "doc.qty_placeholder":     { th: "จำนวน",               en: "Qty" },
  "doc.stock_remaining":     { th: "คงเหลือ:",            en: "Stock:" },
  "doc.add_product":         { th: "เพิ่มสินค้า",         en: "Add Item" },
  "doc.select_customer_first": { th: "กรุณาเลือกลูกค้าก่อนเพิ่มสินค้า", en: "Please select a customer before adding items" },
  "doc.duplicate_product":   { th: "สินค้านี้ถูกเพิ่มในรายการแล้ว — กรุณาเพิ่มจำนวนในแถวเดิมแทน", en: "This product is already in the list — please update the quantity on the existing row instead" },
  "doc.insufficient_row":    { th: "⚠️ จำนวนสินค้าไม่เพียงพอ — มีในสต๊อก {available} {unit} แต่สั่ง {requested} {unit}", en: "⚠️ Insufficient stock — {available} {unit} in stock but ordered {requested} {unit}" },
  "doc.insufficient_title":  { th: "⚠️ จำนวนสินค้าไม่เพียงพอ ({count} รายการ)", en: "⚠️ Insufficient stock ({count} items)" },
  "doc.insufficient_line":   { th: "{name}: สั่ง {requested} {unit} / มีในสต๊อก {available} {unit}", en: "{name}: ordered {requested} {unit} / in stock {available} {unit}" },
  "doc.insufficient_hint":   { th: "ส่งคำสั่งซื้อทันทีไม่ได้ — กด \"บันทึกฉบับร่าง\" เพื่อเก็บไว้ก่อน (ยังไม่ตัดสต๊อก)", en: "Cannot submit immediately — click \"Save Draft\" to keep it for now (stock not deducted yet)" },
  "doc.show_tax_id":         { th: "แสดงเลขผู้เสียภาษีของลูกค้าในเอกสาร", en: "Show customer tax ID on document" },
  "doc.no_tax_id_hint":      { th: "ลูกค้ารายนี้ยังไม่มีเลขผู้เสียภาษีในระบบ — เพิ่มได้ที่หน้าข้อมูลลูกค้า", en: "This customer has no tax ID on record — add one on the customer page" },
  "doc.select_customer_hint":{ th: "กรุณาเลือกลูกค้าก่อน จึงจะแสดงเลขผู้เสียภาษี", en: "Select a customer first to show tax ID" },
  "doc.include_vat":         { th: "รวมภาษี VAT",         en: "Include VAT" },
  "doc.discount_title":      { th: "ส่วนลด",              en: "Discount" },
  "doc.discount_pct":        { th: "% ส่วนลด",            en: "Discount %" },
  "doc.discount_amt":        { th: "ยอดบาท",              en: "Amount (฿)" },
  "doc.other_expenses":      { th: "ค่าใช้จ่ายอื่น ๆ (เช่น ค่าขนส่ง)", en: "Other Expenses (e.g. shipping)" },
  "doc.item_name_placeholder": { th: "ชื่อรายการ",        en: "Item name" },
  "doc.notes_optional":      { th: "หมายเหตุ (ถ้ามี)",     en: "Notes (optional)" },
  "doc.notes":               { th: "หมายเหตุ",            en: "Notes" },
  "doc.contract_days":       { th: "ระยะเวลาสัญญา (วัน)",  en: "Contract Period (days)" },
  "doc.save_draft":          { th: "บันทึกฉบับร่าง",      en: "Save Draft" },
  "doc.submit_order":        { th: "ส่งคำสั่งซื้อ",       en: "Submit Order" },
  "doc.submit_for_approval": { th: "ส่งเพื่ออนุมัติ",     en: "Submit for Approval" },
  "doc.insufficient_disabled_title": { th: "จำนวนสินค้าไม่เพียงพอ", en: "Insufficient stock" },
  "doc.select_customer_err": { th: "กรุณาเลือกลูกค้า",     en: "Please select a customer" },
  "doc.select_item_err":     { th: "กรุณาเพิ่มสินค้าอย่างน้อย 1 รายการ", en: "Please add at least one item" },
  "doc.select_product_err":  { th: "กรุณาเลือกสินค้าให้ครบทุกรายการ", en: "Please select a product for every row" },
  "doc.insufficient_submit_err": { th: "จำนวนสินค้าไม่เพียงพอ — ปรับจำนวนสินค้าใหม่ หรือกด \"บันทึกฉบับร่าง\"", en: "Insufficient stock — adjust quantities or click \"Save Draft\"" },
  "doc.reason_required":    { th: "กรุณาระบุเหตุผล",       en: "Please provide a reason" },
  "doc.approve_ok":          { th: "อนุมัติเรียบร้อย — กด \"แปลงเป็นคำสั่งซื้อ\" เพื่อออกคำสั่งซื้อต่อได้เลย", en: "Approved — click \"Convert to Order\" to place an order right away" },
  "doc.reject_ok":           { th: "ปฏิเสธเรียบร้อย",     en: "Rejected" },
  "doc.approve_failed":      { th: "อนุมัติไม่สำเร็จ",     en: "Approval failed" },
  "doc.reject_failed":       { th: "ปฏิเสธไม่สำเร็จ",      en: "Rejection failed" },
  "doc.save_failed":         { th: "บันทึกไม่สำเร็จ",      en: "Save failed" },
  "doc.saving_ellipsis":     { th: "บันทึก…",             en: "Saving…" },
  "doc.saving_dots2":        { th: "บันทึก...",           en: "Saving..." },
  "doc.generating_pdf":      { th: "กำลังสร้าง PDF…",     en: "Generating PDF…" },
  "doc.loading_data":        { th: "กำลังโหลดข้อมูล...",  en: "Loading data..." },
  "doc.from_quotation_title":{ th: "สินค้าจากใบเสนอราคา{number}", en: "Items from quotation{number}" },
  "doc.from_quotation_hint": { th: "รายการด้านล่างถูกเติมจากใบเสนอราคาที่อนุมัติแล้ว — ปรับแก้จำนวน เพิ่ม หรือลบได้ก่อนส่งคำสั่งซื้อ", en: "Items below were prefilled from the approved quotation — adjust quantities, add, or remove before submitting" },
  "doc.from_quotation_skip": { th: "ℹ️ คำสั่งซื้อนี้แปลงจากใบเสนอราคาที่อนุมัติแล้ว จะข้ามขั้นตรวจสอบ ส่งไปยังขั้นยืนยันการขายโดยตรง", en: "ℹ️ This order is converted from an approved quotation — it skips the review step and goes straight to sale confirmation" },

  // Customer requests
  "cr.title":              { th: "คำขอเพิ่มลูกค้า",       en: "Customer Requests" },
  "cr.title_review":       { th: "พิจารณาคำขอเพิ่มลูกค้า", en: "Review Customer Request" },
  "cr.col.company":        { th: "บริษัท",               en: "Company" },
  "cr.col.requester":      { th: "ผู้ขอ",                en: "Requested By" },
  "cr.col.contact":        { th: "ผู้ติดต่อ",            en: "Contact" },
  "cr.col.phone":          { th: "โทร",                  en: "Phone" },
  "cr.col.requested_at":   { th: "วันที่ขอ",             en: "Requested On" },
  "cr.no_pending":         { th: "ไม่มีคำขอที่รออนุมัติ", en: "No pending requests" },
  "cr.requested_by":       { th: "ขอโดย:",               en: "Requested by:" },
  "cr.field.address":      { th: "ที่อยู่",              en: "Address" },
  "cr.field.contact":      { th: "ผู้ติดต่อ",            en: "Contact" },
  "cr.field.phone":        { th: "โทรศัพท์",             en: "Phone" },
  "cr.field.email":        { th: "อีเมล",                en: "Email" },
  "cr.field.drug_license":  { th: "เลขใบอนุญาตขายยา",     en: "Drug License No." },
  "cr.img.location":       { th: "รูปสถานที่",           en: "Location Photo" },
  "cr.img.drug_license":    { th: "ใบอนุญาตขายยา",        en: "Drug License" },
  "cr.img.hospital_license":{ th: "ใบอนุญาตสถานพยาบาล",  en: "Hospital License" },
  "cr.not_approve":        { th: "ไม่อนุมัติ",           en: "Reject" },
  "cr.approve":            { th: "อนุมัติ",              en: "Approve" },
  "cr.reject_reason":      { th: "เหตุผลที่ไม่อนุมัติ *", en: "Rejection Reason *" },
  "cr.confirm":            { th: "ยืนยัน",               en: "Confirm" },

  // Teams
  "teams.title":            { th: "จัดการทีม",           en: "Manage Teams" },
  "teams.title_all":        { th: "ทีมทั้งหมด",          en: "All Teams" },
  "teams.all_count":        { th: "ทั้งหมด {count} ทีม", en: "{count} teams total" },
  "teams.create":           { th: "สร้างทีม",            en: "Create Team" },
  "teams.create_new":       { th: "สร้างทีมใหม่",        en: "Create New Team" },
  "teams.edit":             { th: "แก้ไขทีม",            en: "Edit Team" },
  "teams.edit_name":        { th: "แก้ไขชื่อทีม",        en: "Edit Team Name" },
  "teams.members":          { th: "สมาชิก",              en: "Members" },
  "teams.members_count":    { th: "สมาชิก ({count})",    en: "Members ({count})" },
  "teams.more_members":     { th: "และอีก {count} คน",   en: "and {count} more" },
  "teams.no_teams":         { th: "ยังไม่มีทีม",         en: "No teams yet" },
  "teams.no_members":       { th: "ยังไม่มีสมาชิก",      en: "No members yet" },
  "teams.add_member":       { th: "เพิ่มสมาชิก",         en: "Add Member" },
  "teams.select_user":      { th: "-- เลือกผู้ใช้ --",   en: "-- Select User --" },
  "teams.add":              { th: "เพิ่ม",               en: "Add" },
  "teams.no_available_users": { th: "ไม่มีผู้ใช้ที่สามารถเพิ่มได้ — ทุกคนถูกจัดเข้าทีมแล้ว (1 คนต่อ 1 ทีม)", en: "No users available — everyone is already assigned to a team (1 person per team)" },
  "teams.field.name":       { th: "ชื่อทีม *",           en: "Team Name *" },
  "teams.field.description": { th: "คำอธิบาย",           en: "Description" },
  "teams.confirm_delete":   { th: "ลบทีม {name}?",       en: "Delete team {name}?" },
  "teams.confirm_remove_member": { th: "นำสมาชิกออกจากทีม?", en: "Remove member from team?" },

  // Reports — common
  "reports.title":               { th: "รายงาน",                en: "Reports" },
  "reports.title_team":          { th: "รายงานทีม",             en: "Team Reports" },

  // Admin/CFO reports tabs
  "reports.tab.orders":          { th: "รายงานคำสั่งซื้อ",       en: "Order Report" },
  "reports.tab.completed":       { th: "คำสั่งซื้อสำเร็จ",       en: "Completed Orders" },
  "reports.tab.customers":       { th: "ลูกค้า",                en: "Customers" },
  "reports.tab.products":        { th: "สินค้า",                en: "Products" },
  "reports.tab.stock":           { th: "สต๊อกต่ำ",              en: "Low Stock" },
  "reports.orders_by_status":    { th: "สัดส่วนคำสั่งซื้อตามสถานะ", en: "Orders by Status" },
  "reports.summary_by_status":   { th: "สรุปจำนวนตามสถานะ",      en: "Summary by Status" },
  "reports.completed_total":     { th: "คำสั่งซื้อสำเร็จทั้งหมด", en: "Total completed orders" },
  "reports.records_suffix":      { th: "รายการ",                en: "records" },
  "reports.total_sum":           { th: "รวมยอด",                en: "Total" },
  "reports.top_customers":       { th: "ลูกค้า Top 10 (ซื้อสูงสุด)", en: "Top 10 Customers (by purchase)" },
  "reports.top_products":        { th: "สินค้าขายดี Top 10",     en: "Top 10 Products" },
  "reports.low_stock_title":     { th: "สินค้าสต๊อกต่ำ (น้อยกว่า 10)", en: "Low Stock Products (under 10)" },
  "reports.no_low_stock":        { th: "ไม่มีสินค้าสต๊อกต่ำ",    en: "No low-stock products" },
  "reports.col.rank":            { th: "อันดับ",                en: "Rank" },
  "reports.col.order_count":     { th: "จำนวนครั้ง",            en: "Order Count" },
  "reports.col.total_sales":     { th: "ยอดรวม",                en: "Total Sales" },
  "reports.col.stock":           { th: "คงเหลือ",               en: "Stock" },
  "reports.col.unit":            { th: "หน่วย",                 en: "Unit" },
  "reports.col.price":           { th: "ราคา",                  en: "Price" },

  // Manager reports
  "reports.tab.overview":        { th: "ภาพรวม",                en: "Overview" },
  "reports.tab.team_sales":      { th: "ยอดขายทีม",             en: "Team Sales" },
  "reports.tab.approval":        { th: "การอนุมัติ",            en: "Approvals" },
  "reports.quotation_status":    { th: "สถานะใบเสนอราคา",       en: "Quotation Status" },
  "reports.order_status":        { th: "สถานะคำสั่งซื้อ",       en: "Order Status" },
  "reports.sales_per_member":     { th: "ยอดขายของพนักงานแต่ละคน", en: "Sales per Team Member" },
  "reports.col.employee":        { th: "พนักงาน",               en: "Employee" },
  "reports.col.order_count_full":{ th: "จำนวนคำสั่งซื้อ",       en: "Order Count" },
  "reports.col.sales":           { th: "ยอดขาย",                en: "Sales" },

  // CFO reports filter UI
  "reports.filters":              { th: "ตัวกรอง",              en: "Filters" },
  "reports.reset":                { th: "รีเซ็ต",               en: "Reset" },
  "reports.hide":                 { th: "ซ่อน",                 en: "Hide" },
  "reports.show":                 { th: "แสดง",                 en: "Show" },
  "reports.quick_range":          { th: "ช่วงเร็ว:",            en: "Quick range:" },
  "reports.quick.today":          { th: "วันนี้",               en: "Today" },
  "reports.quick.week":           { th: "7 วัน",                en: "7 days" },
  "reports.quick.month":          { th: "เดือนนี้",             en: "This month" },
  "reports.quick.year":           { th: "ปีนี้",                en: "This year" },
  "reports.quick.all":            { th: "ทั้งหมด",              en: "All" },
  "reports.from_date":            { th: "จากวันที่",            en: "From Date" },
  "reports.to_date":              { th: "ถึงวันที่",            en: "To Date" },
  "reports.zone":                 { th: "เขตการขาย",            en: "Sales Zone" },
  "reports.team":                 { th: "ทีม",                  en: "Team" },
  "reports.province":             { th: "จังหวัด",              en: "Province" },
  "reports.region":                { th: "ภาค",                  en: "Region" },
  "reports.status":               { th: "สถานะ",                en: "Status" },
  "reports.all_option":           { th: "ทั้งหมด",              en: "All" },
  "reports.apply_filters":        { th: "ปรับใช้ตัวกรอง",       en: "Apply Filters" },
  "reports.loading_ellipsis":     { th: "กำลังโหลด…",           en: "Loading…" },

  // Activity logs
  "logs.title":           { th: "บันทึกการใช้งาน",       en: "Activity Logs" },
  "logs.col.time":         { th: "เวลา",                 en: "Time" },
  "logs.col.user":         { th: "ผู้ใช้",                en: "User" },
  "logs.col.role":         { th: "บทบาท",                en: "Role" },
  "logs.col.action":       { th: "การกระทำ",             en: "Action" },
  "logs.col.detail":       { th: "รายละเอียด",           en: "Detail" },
  "logs.all_actions":      { th: "การกระทำทั้งหมด",       en: "All Actions" },
  "logs.no_logs":          { th: "ไม่พบบันทึก",           en: "No logs found" },
  "logs.action.login":                      { th: "เข้าสู่ระบบ",             en: "Login" },
  "logs.action.logout":                     { th: "ออกจากระบบ",             en: "Logout" },
  "logs.action.user_create":                { th: "สร้างผู้ใช้",             en: "Create User" },
  "logs.action.user_update":                { th: "แก้ไขผู้ใช้",             en: "Update User" },
  "logs.action.user_update_password":       { th: "แก้ไขผู้ใช้ + รหัสผ่าน",   en: "Update User + Password" },
  "logs.action.user_deactivate":            { th: "ปิดผู้ใช้",               en: "Deactivate User" },
  "logs.action.team_create":                { th: "สร้างทีม",                en: "Create Team" },
  "logs.action.team_update":                { th: "แก้ไขทีม",                en: "Update Team" },
  "logs.action.team_delete":                { th: "ลบทีม",                  en: "Delete Team" },
  "logs.action.product_create":             { th: "สร้างสินค้า",             en: "Create Product" },
  "logs.action.product_update":             { th: "แก้ไขสินค้า",             en: "Update Product" },
  "logs.action.product_delete":             { th: "ลบสินค้า",               en: "Delete Product" },
  "logs.action.customer_create":            { th: "เพิ่มลูกค้า",             en: "Add Customer" },
  "logs.action.customer_update":            { th: "แก้ไขลูกค้า",             en: "Update Customer" },
  "logs.action.customer_delete":            { th: "ลบลูกค้า",               en: "Delete Customer" },
  "logs.action.customer_request_create":    { th: "ส่งคำขอลูกค้า",           en: "Submit Customer Request" },
  "logs.action.customer_request_approve":   { th: "อนุมัติคำขอลูกค้า",        en: "Approve Customer Request" },
  "logs.action.customer_request_reject":    { th: "ปฏิเสธคำขอลูกค้า",         en: "Reject Customer Request" },
  "logs.action.quotation_create_draft":     { th: "สร้างใบเสนอราคา (ร่าง)",   en: "Create Quotation (Draft)" },
  "logs.action.quotation_create_pending":   { th: "สร้างใบเสนอราคา",          en: "Create Quotation" },
  "logs.action.quotation_create_approved":  { th: "สร้างใบเสนอราคา",          en: "Create Quotation" },
  "logs.action.quotation_create_auto":      { th: "สร้าง+อนุมัติอัตโนมัติ",    en: "Create + Auto-Approve" },
  "logs.action.quotation_update":           { th: "แก้ไขใบเสนอราคา",          en: "Update Quotation" },
  "logs.action.quotation_approve":          { th: "อนุมัติใบเสนอราคา",        en: "Approve Quotation" },
  "logs.action.quotation_reject":           { th: "ปฏิเสธใบเสนอราคา",         en: "Reject Quotation" },
  "logs.action.order_create":               { th: "สร้างคำสั่งซื้อ",          en: "Create Order" },
  "logs.action.order_create_auto":          { th: "สร้าง+อนุมัติอัตโนมัติ",    en: "Create + Auto-Approve" },
  "logs.action.order_review_pass":          { th: "ตรวจสอบผ่าน",             en: "Review Passed" },
  "logs.action.order_review_reject":        { th: "ตรวจสอบไม่ผ่าน",           en: "Review Rejected" },
  "logs.action.order_confirm":              { th: "ยืนยันการขาย",            en: "Confirm Sale" },
  "logs.action.order_cancel":               { th: "ยกเลิกคำสั่งซื้อ",         en: "Cancel Order" },

  // Admin customers
  "ac.back":               { th: "← กลับ",               en: "← Back" },
  "ac.add_customer":       { th: "เพิ่มลูกค้า",           en: "Add Customer" },
  "ac.col.company":        { th: "บริษัท",               en: "Company" },
  "ac.col.contact":        { th: "ผู้ติดต่อ",            en: "Contact" },
  "ac.col.phone":          { th: "โทรศัพท์",             en: "Phone" },
  "ac.col.email":          { th: "อีเมล",                en: "Email" },
  "ac.col.address":        { th: "ที่อยู่",              en: "Address" },
  "ac.no_customers":       { th: "ไม่พบลูกค้า",          en: "No customers found" },
  "ac.edit":               { th: "แก้ไข",                en: "Edit" },

  // Admin products
  "ap.add_product":        { th: "เพิ่มสินค้า",          en: "Add Product" },
  "ap.col.code":           { th: "รหัส",                 en: "Code" },
  "ap.col.name":           { th: "ชื่อสินค้า",           en: "Product Name" },
  "ap.col.category":       { th: "หมวดหมู่",             en: "Category" },
  "ap.col.stock":          { th: "คงเหลือ",              en: "Stock" },
  "ap.col.cost":           { th: "ต้นทุน",               en: "Cost" },
  "ap.col.sale_price":     { th: "ราคาขาย",              en: "Sale Price" },
  "ap.col.status":         { th: "สถานะ",                en: "Status" },
  "ap.status.available":   { th: "พร้อมขาย",             en: "Available" },
  "ap.status.off":         { th: "ปิด",                  en: "Off" },
  "ap.no_products":        { th: "ไม่พบสินค้า",          en: "No products found" },
  "ap.edit_title":         { th: "แก้ไขสินค้า",           en: "Edit Product" },
  "ap.add_new_title":      { th: "เพิ่มสินค้าใหม่",       en: "Add New Product" },
  "ap.field.code":         { th: "รหัสสินค้า",            en: "Product Code" },
  "ap.field.unit":         { th: "หน่วย (เช่น กล่อง)",     en: "Unit (e.g. box)" },
  "ap.field.name":         { th: "ชื่อสินค้า",            en: "Product Name" },
  "ap.field.qty":          { th: "จำนวนสินค้าคงเหลือ",     en: "Quantity in Stock" },
  "ap.qty_hint":           { th: "การเปลี่ยนจำนวนจะถูกบันทึกใน Stock Log", en: "Quantity changes are logged in Stock Log" },
  "ap.field.lot":          { th: "เลขล็อต",               en: "Lot Number" },
  "ap.field.mfg_date":     { th: "วันผลิต",               en: "Manufacture Date" },
  "ap.field.exp_date":     { th: "วันหมดอายุ",            en: "Expiry Date" },
  "ap.field.cost_price":   { th: "ราคาต้นทุน (บาท)",       en: "Cost Price (฿)" },
  "ap.cost_hint":          { th: "เห็นได้แค่ Admin / CFO", en: "Visible to Admin / CFO only" },
  "ap.field.sale_price":   { th: "ราคาขาย (บาท)",         en: "Sale Price (฿)" },
  "ap.field.category":     { th: "หมวดหมู่",              en: "Category" },
  "ap.no_category":        { th: "-- ไม่มีหมวด --",       en: "-- No Category --" },
  "ap.field.image":        { th: "รูปสินค้า",             en: "Product Image" },
  "ap.upload":             { th: "อัพโหลดรูป",            en: "Upload Image" },
  "ap.confirm_delete":     { th: "ลบสินค้า {name}?",       en: "Delete product {name}?" },

  // Layout
  "layout.loading":        { th: "กำลังโหลด...",         en: "Loading..." },

  // TopBar — settings menu
  "topbar.settings":       { th: "ตั้งค่า",              en: "Settings" },

  // Settings page
  "settings.title":          { th: "ตั้งค่าบัญชี",         en: "Account Settings" },
  "settings.profile_info":   { th: "ข้อมูลส่วนตัว",        en: "Profile Info" },
  "settings.email":          { th: "อีเมล",               en: "Email" },
  "settings.email_hint":     { th: "ไม่สามารถเปลี่ยนอีเมลได้", en: "Email cannot be changed" },
  "settings.first_name":     { th: "ชื่อ",                en: "First Name" },
  "settings.last_name":      { th: "นามสกุล",             en: "Last Name" },
  "settings.phone":          { th: "เบอร์โทรศัพท์",       en: "Phone" },
  "settings.role":           { th: "บทบาท",               en: "Role" },
  "settings.team":           { th: "ทีม",                 en: "Team" },
  "settings.save_profile":   { th: "บันทึกข้อมูล",        en: "Save Profile" },
  "settings.change_password":{ th: "เปลี่ยนรหัสผ่าน",     en: "Change Password" },
  "settings.new_password":   { th: "รหัสผ่านใหม่",        en: "New Password" },
  "settings.confirm_password": { th: "ยืนยันรหัสผ่านใหม่", en: "Confirm New Password" },
  "settings.password_hint":  { th: "อย่างน้อย 6 ตัวอักษร (เว้นว่างไว้หากไม่ต้องการเปลี่ยน)", en: "At least 6 characters (leave blank to keep current)" },
  "settings.password_mismatch": { th: "รหัสผ่านไม่ตรงกัน", en: "Passwords don't match" },
  "settings.update_password":{ th: "อัปเดตรหัสผ่าน",      en: "Update Password" },
  "settings.profile_saved":  { th: "บันทึกข้อมูลเรียบร้อย", en: "Profile saved" },
  "settings.password_saved": { th: "เปลี่ยนรหัสผ่านเรียบร้อย", en: "Password changed" },
  "settings.save_failed":    { th: "บันทึกไม่สำเร็จ",      en: "Save failed" },
};

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined,
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  // Always start with "th" so the server-rendered HTML and the initial client
  // render are identical (no hydration mismatch). After hydration we read
  // localStorage and switch to the user's saved language.
  const [lang, setLang] = useState<Lang>("th");

  useEffect(() => {
    // Read the saved language once, after the component mounts on the client.
    const saved = localStorage.getItem("lang") as Lang | null;
    if (saved && saved !== lang) {
      setLang(saved);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    try {
      localStorage.setItem("lang", lang);
    } catch { }
  }, [lang]);

  const t = (key: string) => {
    const entry = translations[key];
    if (entry) return lang === "th" ? entry.th : entry.en;
    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

export default LanguageContext;
